spring:
  application:
    name: weather
  datasource:
    url: jdbc:postgresql://localhost:5432/weather
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          format_sql: true
      database: postgresql

weather.properties:
  hello-message: "Hello world"